AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - '**/config.ru'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/faraday/http/signatures/signature_signer.rb'
